### ISSUE TITLE
Consider adding Skyeng-words to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [aCLr/skyeng-words-exporter#1]
Hey @aCLr, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by antonio-antuan** [comment]
Hey! Glad to use your library :)

I'm not sure that my project worth it to be noticed in COMMUNITY.md of your repo. It's just a... script for private purposes and I do not think that anyone will use it.

The first think that I will do if I develop any significant project is write about it there to make SeaORM more widely spread :)

**Comment by billy1624** [comment]
Hey @aCLr, thanks for the support!
